# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Velascat
"""
run_status.py — generic managed-repo run_status.json contract model.

This is the ENTRY POINT for OperationsCenter audit output discovery.

Discovery chain:
    run_status.json
      → field: artifact_manifest_path
        → artifact_manifest.json

Design rules:
- artifact_manifest_path is required for all Phase 5+ managed runs.
- During transition, pre-Phase-5 producers emit run_status.json without
  this field. The model accepts it as Optional only to allow reading
  legacy files. Compliant producers MUST populate it.
- status uses RunStatus vocabulary. Pre-Phase-5 producers emit
  "in_progress" (legacy); Phase 5 must switch to "running".
"""

from __future__ import annotations

from datetime import datetime
from typing import Any

from pydantic import BaseModel, Field, field_validator

from .vocabulary import RunStatus

_CONTRACT_NAME = "managed-repo-audit"
_SCHEMA_VERSION = "1.0"


class ManagedRunStatus(BaseModel):
    """Schema for run_status.json as defined by the managed-repo audit contract.

    All managed-repo producers must conform to this schema after Phase 5.
    OpsCenter reads this file first; the artifact_manifest_path field
    leads to the artifact manifest.

    Generic fields: applicable to any managed repo.
    Producer-specific fields may be added in metadata.
    """

    schema_version: str = Field(
        default=_SCHEMA_VERSION,
        description="Contract schema version.",
    )
    contract_name: str = Field(
        default=_CONTRACT_NAME,
        description="Identifies this as a managed-repo-audit contract file.",
    )
    producer: str = Field(
        description="Managed repo identifier as configured in the operator's binding.",
    )
    repo_id: str = Field(
        description="Stable repo identifier matching the managed repo config.",
    )
    run_id: str = Field(
        description="UUID hex generated by OperationsCenter before invocation.",
    )
    audit_type: str = Field(
        description="Audit type identifier (e.g. 'representative').",
    )
    status: RunStatus = Field(
        description=(
            "Run lifecycle status. Canonical values: pending, running, completed, "
            "failed, interrupted, unknown. Legacy: 'in_progress' (pre-Phase-5 producers)."
        ),
    )
    current_phase: str | None = Field(
        default=None,
        description="Current named phase within the run, if available.",
    )
    started_at: datetime | None = Field(
        default=None,
        description="ISO 8601 UTC timestamp when the run started.",
    )
    updated_at: datetime | None = Field(
        default=None,
        description="ISO 8601 UTC timestamp of the most recent status update.",
    )
    completed_at: datetime | None = Field(
        default=None,
        description="ISO 8601 UTC timestamp when the run reached a terminal state.",
    )
    error: str | None = Field(
        default=None,
        description="Human-readable error summary on failure.",
    )
    traceback: str | None = Field(
        default=None,
        description="Full traceback on exception failure.",
    )
    artifact_manifest_path: str | None = Field(
        default=None,
        description=(
            "Path to artifact_manifest.json for this run. "
            "REQUIRED for all managed runs after Phase 5 implementation. "
            "None only during the pre-Phase-5 transition period."
        ),
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Producer-specific metadata (not read by generic OpsCenter logic).",
    )

    model_config = {"frozen": False}

    @field_validator("status", mode="before")
    @classmethod
    def _accept_legacy_in_progress(cls, v: object) -> object:
        # Pre-Phase-5 producers emit "in_progress"; map to the enum value.
        # The enum has IN_PROGRESS_LEGACY = "in_progress" so this is a no-op
        # at the value level, but it's explicit about the intent.
        return v

    @property
    def is_terminal(self) -> bool:
        return self.status in (
            RunStatus.COMPLETED,
            RunStatus.FAILED,
            RunStatus.INTERRUPTED,
        )

    @property
    def has_manifest(self) -> bool:
        return self.artifact_manifest_path is not None

    @property
    def is_compliant(self) -> bool:
        """True if this run_status.json meets the full Phase 5 contract."""
        return self.has_manifest and self.status != RunStatus.IN_PROGRESS_LEGACY


__all__ = ["ManagedRunStatus"]
