# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Velascat
"""Command resolution — produce a ManagedAuditInvocationRequest from config.

Given a repo_id, audit_type, and run_id, this module:
  1. Loads the managed repo config (Phase 1).
  2. Verifies audit capability and audit_type support.
  3. Checks command_status policy.
  4. Injects AUDIT_RUN_ID into the environment.
  5. Returns a validated ManagedAuditInvocationRequest.

Nothing is executed here.

Command status policy
---------------------
  verified          Always allowed.
  not_yet_run       Allowed by default (allow_not_yet_run=True).
                    Pass allow_not_yet_run=False to block it.
  unknown           Always blocked — silently accepting unknown commands
                    would violate the contract boundary.
  needs_confirmation Always blocked — requires explicit human approval before
                    the command can be added to the verified set.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from operations_center.managed_repos.loader import load_managed_repo_config

from .contracts import ManagedAuditInvocationRequest
from .errors import (
    ManagedAuditCommandUnavailableError,
    ManagedAuditTypeUnsupportedError,
    ManagedRepoCapabilityError,
    ManagedRepoNotFoundError,
)

_ALWAYS_BLOCKED: frozenset[str] = frozenset({"unknown", "needs_confirmation"})


def resolve_invocation_request(
    repo_id: str,
    audit_type: str,
    run_id: str,
    *,
    config_dir: Path | str | None = None,
    allow_not_yet_run: bool = True,
    extra_env: dict[str, str] | None = None,
    metadata: dict[str, Any] | None = None,
) -> ManagedAuditInvocationRequest:
    """Resolve a managed audit invocation request from config.

    Parameters
    ----------
    repo_id:
        Identifies the managed repo (must have a config file).
    audit_type:
        The audit type to invoke.
    run_id:
        UUID hex generated by OpsCenter.  Injected as AUDIT_RUN_ID.
    config_dir:
        Override for the managed repo config directory.
    allow_not_yet_run:
        If True (default), audit types with command_status='not_yet_run'
        are allowed for contract generation.  Set False to require
        'verified' status only.
    extra_env:
        Additional environment variables merged into the request env.
        AUDIT_RUN_ID is always injected regardless of this value.
    metadata:
        Arbitrary metadata forwarded to the invocation request.

    Raises
    ------
    ManagedRepoNotFoundError
        No config file found for repo_id.
    ManagedRepoCapabilityError
        The repo does not advertise the 'audit' capability.
    ManagedAuditTypeUnsupportedError
        The audit_type is not declared in the repo config.
    ManagedAuditCommandUnavailableError
        The command_status is blocked ('unknown' or 'needs_confirmation'),
        or is 'not_yet_run' and allow_not_yet_run=False.
    """
    try:
        config = load_managed_repo_config(repo_id, config_dir=config_dir)
    except FileNotFoundError as exc:
        raise ManagedRepoNotFoundError(
            f"No managed repo config found for repo_id={repo_id!r}"
        ) from exc

    if not config.has_capability("audit"):
        raise ManagedRepoCapabilityError(
            f"Managed repo {repo_id!r} does not advertise 'audit' capability"
        )

    if config.audit is None:  # guaranteed by has_capability check above, but guard for type narrowing
        raise RuntimeError(f"config.audit unexpectedly None for repo {repo_id!r}")
    at = config.audit.get_audit_type(audit_type)
    if at is None:
        raise ManagedAuditTypeUnsupportedError(
            f"audit_type={audit_type!r} is not declared in managed repo {repo_id!r}. "
            f"Known types: {config.audit_type_names}"
        )

    _check_command_status(at.command_status, audit_type, allow_not_yet_run)

    env: dict[str, str] = dict(extra_env or {})
    env["AUDIT_RUN_ID"] = run_id

    return ManagedAuditInvocationRequest(
        repo_id=repo_id,
        audit_type=audit_type,
        run_id=run_id,
        working_directory=at.working_dir,
        command=at.command,
        env=env,
        expected_output_dir=at.output_dir,
        metadata=dict(metadata or {}),
    )


def _check_command_status(
    status: str,
    audit_type: str,
    allow_not_yet_run: bool,
) -> None:
    if status in _ALWAYS_BLOCKED:
        raise ManagedAuditCommandUnavailableError(
            f"audit_type={audit_type!r} has command_status={status!r} which is "
            "blocked. Resolve the command evidence before generating invocation "
            "requests."
        )
    if status == "not_yet_run" and not allow_not_yet_run:
        raise ManagedAuditCommandUnavailableError(
            f"audit_type={audit_type!r} has command_status='not_yet_run' and "
            "allow_not_yet_run=False. Run the audit at least once to verify "
            "the command before strict contract generation."
        )
