# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 ProtocolWarden
"""ManagedAuditInvocationRequest — the OpsCenter-side audit invocation contract.

This model captures everything OpsCenter knows at the moment it decides to
invoke a managed repo audit.  It is NOT an executor — nothing is run here.
Phase 6 dispatch consumes this model to actually launch the command.
"""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field, model_validator


class ManagedAuditInvocationRequest(BaseModel):
    """Validated contract object for a pending managed audit invocation.

    Fields
    ------
    repo_id
        Identifies which managed repo will run the audit.
    audit_type
        Which audit type to invoke (e.g. "representative").
    run_id
        UUID hex generated by OpsCenter before invocation.
        Must be passed as AUDIT_RUN_ID env var.
    working_directory
        Directory from which the command should be executed.
    command
        The external command string to invoke.  Not executed here.
    env
        Environment variables to set when invoking the command.
        Must include AUDIT_RUN_ID.
    expected_output_dir
        Base directory where run_status.json will appear after the run.
        For bucket-based outputs the actual bucket subdirectory is
        determined at runtime; Phase 6 discovers it within this directory.
    metadata
        Arbitrary caller-supplied metadata (channel_slug, etc.).
    """

    repo_id: str
    audit_type: str
    run_id: str
    working_directory: str
    command: str
    env: dict[str, str] = Field(default_factory=dict)
    expected_output_dir: str
    metadata: dict[str, Any] = Field(default_factory=dict)

    @model_validator(mode="after")
    def _audit_run_id_must_be_injected(self) -> "ManagedAuditInvocationRequest":
        if "AUDIT_RUN_ID" not in self.env:
            raise ValueError("env must contain AUDIT_RUN_ID")
        if self.env["AUDIT_RUN_ID"] != self.run_id:
            raise ValueError("AUDIT_RUN_ID in env must match run_id")
        return self
